"""Migration Clothing vers Product/ProductVariant

Revision ID: 4f60b3d9ccc3
Revises: a66e3449b55d
Create Date: 2026-07-31 23:39:40.653632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f60b3d9ccc3'
down_revision: Union[str, Sequence[str], None] = 'a66e3449b55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothingimage_clothing_id'), table_name='clothingimage')
    op.drop_table('clothingimage')
    op.drop_index(op.f('ix_clothing_collection_id'), table_name='clothing')
    op.drop_table('clothing')
    op.execute("DROP TYPE item")
    op.execute("DROP TYPE size")
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item', sa.Enum('T_SHIRT', 'SWEATS', 'JACKETS', 'PANTS', 'SHORTS', 'UNDERWEAR', 'ACCESSORIES', name='item'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_collection_id'), 'product', ['collection_id'], unique=False)
    op.create_table('productimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productimage_product_id'), 'productimage', ['product_id'], unique=False)
    op.create_table('productvariant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='size'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productvariant_product_id'), 'productvariant', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item', postgresql.ENUM('T_SHIRT', 'SWEATS', 'JACKETS', 'PANTS', 'SHORTS', 'UNDERWEAR', 'ACCESSORIES', name='item'), autoincrement=False, nullable=False),
    sa.Column('size', postgresql.ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL', name='size'), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('clothing_collection_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('clothing_pkey'))
    )
    op.create_index(op.f('ix_clothing_collection_id'), 'clothing', ['collection_id'], unique=False)
    op.create_table('clothingimage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_cover', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('clothing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.id'], name=op.f('clothingimage_clothing_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('clothingimage_pkey'))
    )
    op.create_index(op.f('ix_clothingimage_clothing_id'), 'clothingimage', ['clothing_id'], unique=False)
    op.drop_index(op.f('ix_productvariant_product_id'), table_name='productvariant')
    op.drop_table('productvariant')
    op.drop_index(op.f('ix_productimage_product_id'), table_name='productimage')
    op.drop_table('productimage')
    op.drop_index(op.f('ix_product_collection_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
