"""Ajout du modele address

Revision ID: 52a3a6cda017
Revises: b4b97b98db59
Create Date: 2026-08-13 21:05:21.482802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52a3a6cda017'
down_revision: Union[str, Sequence[str], None] = 'b4b97b98db59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default_shipping', sa.Boolean(), nullable=False),
    sa.Column('is_default_billing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_address_one_default_billing_per_user', 'address', ['user_id'], unique=True, postgresql_where=sa.text('is_default_billing = true'))
    op.create_index('ix_address_one_default_shipping_per_user', 'address', ['user_id'], unique=True, postgresql_where=sa.text('is_default_shipping = true'))
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_index('ix_address_one_default_shipping_per_user', table_name='address', postgresql_where=sa.text('is_default_shipping = true'))
    op.drop_index('ix_address_one_default_billing_per_user', table_name='address', postgresql_where=sa.text('is_default_billing = true'))
    op.drop_table('address')
    # ### end Alembic commands ###
