"""Ajout du champ name dans la table clothes.py

Revision ID: a66e3449b55d
Revises: e2f83b19c488
Create Date: 2026-07-30 16:55:37.934389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a66e3449b55d'
down_revision: Union[str, Sequence[str], None] = 'e2f83b19c488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing', 'name')
    # ### end Alembic commands ###
