"""Verification de mail dans le modele user

Revision ID: b4b97b98db59
Revises: d50e0adcbbb2
Create Date: 2026-08-13 20:14:21.905038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4b97b98db59'
down_revision: Union[str, Sequence[str], None] = 'd50e0adcbbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.execute("UPDATE \"user\" SET email_verified = true WHERE role = 'ADMIN'")
    op.add_column('user', sa.Column('verification_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_verification_token_hash'), 'user', ['verification_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verification_token_hash'), table_name='user')
    op.drop_column('user', 'verification_token_expires_at')
    op.drop_column('user', 'verification_token_hash')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
