"""Changement de la gestion du prix dirrectement au produit, ajout d'un price_overide dans les variants

Revision ID: be3e1738eca0
Revises: 4f60b3d9ccc3
Create Date: 2026-08-04 19:26:17.168606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be3e1738eca0'
down_revision: Union[str, Sequence[str], None] = '4f60b3d9ccc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('productvariant', sa.Column('price_override', sa.Float(), nullable=True))
    op.create_index(op.f('ix_productvariant_sku'), 'productvariant', ['sku'], unique=True)
    op.drop_column('productvariant', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productvariant', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_productvariant_sku'), table_name='productvariant')
    op.drop_column('productvariant', 'price_override')
    op.drop_column('product', 'price')
    # ### end Alembic commands ###
