"""gestion token pour les resets de password

Revision ID: d50e0adcbbb2
Revises: 9179abafb4a1
Create Date: 2026-08-13 18:46:00.247041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd50e0adcbbb2'
down_revision: Union[str, Sequence[str], None] = '9179abafb4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_reset_token_hash'), 'user', ['reset_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_token_hash'), table_name='user')
    op.drop_column('user', 'reset_token_expires_at')
    op.drop_column('user', 'reset_token_hash')
    # ### end Alembic commands ###
